drop table if exists bookmarks;

CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  rating INTEGER
);

INSERT INTO bookmarks (name, url, description, rating)
values
  ('Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', 4.8),
  ('Google', 'https://www.google.com', 'Where we find everything else', 4.9),
  ('MDN', 'https://www.developer.mozilla.org', 'The only place to find we documentatio', 4.7);
  